version: '3.4'
services: 
  app:
    image: ${DOCKER_REGISTRY_REPO:-aspnetcoredemo}:${DOCKER_TAG:-1.0}
    build:
      context: .
      dockerfile: Dockerfile
  test:
    image: ${DOCKER_REGISTRY_REPO:-aspnetcoredemo}:${DOCKER_TAG:-1.0}-test
    build:
        context: .
        dockerfile: Dockerfile
        target: testrunner
    volumes: 
      - ./testresults:/testresults